const articles: Article[] = [
    // article 1
    {
        id: 1,
        title: '让我抱抱，一起温暖，真的好治愈',
        desc: '',
        tag: ['每秒都值得记录', '治愈系', '治愈猫咪'],
        dateTime: '2023-02-27 12:20',
        location: '广东',
        userId: 1,
        userName: '小飞飞爱猫咪',
        isFollow: false,
        avatarUrl: '/avatar/avatar_01.png',
        images: [
            '/article/article01/img_01.jpg',
            '/article/article01/img_02.jpg',
            '/article/article01/img_03.jpg',
            '/article/article01/img_04.jpg',
            '/article/article01/img_05.jpg',
        ],
        favoriteCount: 325,
        collectionCount: 166,
        isFavorite: false,
        isCollection: false,
        comments: [
            {
                userName: '小AA呀',
                avatarUrl: '/avatar/avatar_40.png',
                message: '我的妈呀，太可爱了吧！',
                dateTime: '2023-02-28 07:23',
                location: '南宁',
                favoriteCount: 12,
                isFavorite: false,
                children: [
                    {
                        userName: '小飞飞爱猫咪',
                        avatarUrl: '/avatar/avatar_01.png',
                        message: '谢谢支持～',
                        dateTime: '2023-02-28 08:23',
                        location: '广东',
                        favoriteCount: 3,
                        isFavorite: false,
                    },
                ],
            },
            {
                userName: '天天甜甜',
                avatarUrl: '/avatar/avatar_39.png',
                message: '好可爱啊，好想养一只啊，这么萌的小猫咪是怎么养的啊，我要去up那里去买一只，快快告诉我怎么买？',
                dateTime: '2023-02-28 09:09',
                location: '福建',
                favoriteCount: 7,
                isFavorite: false,
                children: undefined,
            },
            {
                userName: 'Prince小小',
                avatarUrl: '/avatar/avatar_38.png',
                message: '伤过了，不会再相信爱情了。',
                dateTime: '2023-02-28 11:11',
                location: '河北',
                favoriteCount: 1,
                isFavorite: false,
                children: undefined,
            },
            {
                userName: '深海的蓝',
                avatarUrl: '/avatar/avatar_37.png',
                message: '真的好可爱啊，我要养一只',
                dateTime: '2023-02-28 11:34',
                location: '天津',
                favoriteCount: 1,
                isFavorite: false,
                children: undefined,
            },
            {
                userName: 'Look Ground',
                avatarUrl: '/avatar/avatar_36.png',
                message: '支持了',
                dateTime: '2023-02-28 11:35',
                location: '南京',
                favoriteCount: 0,
                isFavorite: false,
                children: undefined,
            },
        ],
    },
    // article 2
    {
        id: 2,
        title: '不愧是网友给的配方，真的香迷糊了',
        desc: '家里鸡蛋不知道怎么吃的，可以去试试这个火腿肠炒蛋，\n我妈说居然这么好吃。\n香辣过瘾真的忒下饭了，做法鸡蛋，你们也去安排起来。',
        tag: ['晚餐', '家常菜', '香肠炒蛋', '鸡蛋的吃法'],
        dateTime: '2023-02-28 09:21',
        location: '广西',
        userId: 2,
        userName: '大厨师小飞象',
        isFollow: false,
        avatarUrl: '/avatar/avatar_02.png',
        images: [
            '/article/article02/img_01.jpg',
            '/article/article02/img_02.jpg',
            '/article/article02/img_03.jpg',
            '/article/article02/img_04.jpg',
            '/article/article02/img_05.jpg',
        ],
        favoriteCount: 1098,
        collectionCount: 208,
        isFavorite: false,
        isCollection: false,
        comments: [
            {
                userName: '胖胖胖',
                avatarUrl: '/avatar/avatar_40.png',
                message: '果断关注，这个博主做的菜真实色香味俱全。每天跟着学做菜，我要做大厨了，啊哈哈～',
                dateTime: '2023-02-28 07:23',
                location: '成都',
                favoriteCount: 45,
                isFavorite: false,
                children: [
                    {
                        userName: '小飞飞爱猫咪',
                        avatarUrl: '/avatar/avatar_01.png',
                        message: '安排起来，这个做法很简单的哦。',
                        dateTime: '2023-02-28 13:23',
                        location: '广东',
                        favoriteCount: 1,
                        isFavorite: false,
                    },
                ],
            },
            {
                userName: '左半',
                avatarUrl: '/avatar/avatar_39.png',
                message: '看着真有食欲',
                dateTime: '2023-02-28 09:09',
                location: '福建',
                favoriteCount: 2,
                isFavorite: false,
                children: undefined,
            },
            {
                userName: 'TTTi',
                avatarUrl: '/avatar/avatar_38.png',
                message: '这个比我做的看着就好吃',
                dateTime: '2023-02-28 11:11',
                location: '河南',
                favoriteCount: 3,
                isFavorite: false,
                children: undefined,
            },
            {
                userName: '衣衣一',
                avatarUrl: '/avatar/avatar_37.png',
                message: '明天我就做这个菜，再做个西兰花',
                dateTime: '2023-02-28 11:34',
                location: '天津',
                favoriteCount: 1,
                isFavorite: false,
                children: undefined,
            },
            {
                userName: '淡淡的',
                avatarUrl: '/avatar/avatar_36.png',
                message: '好好吃的样子啊',
                dateTime: '2023-02-28 11:35',
                location: '安徽',
                favoriteCount: 0,
                isFavorite: false,
                children: undefined,
            },
            {
                userName: 'TyTyTy',
                avatarUrl: '/avatar/avatar_36.png',
                message: '这个做起来简单吗，我想学',
                dateTime: '2023-02-28 11:35',
                location: '河南',
                favoriteCount: 1,
                isFavorite: false,
                children: undefined,
            },
            {
                userName: '马大哈11',
                avatarUrl: '/avatar/avatar_36.png',
                message: '这个好好吃，今晚多吃一碗饭',
                dateTime: '2023-02-28 11:35',
                location: '北京',
                favoriteCount: 1,
                isFavorite: false,
                children: undefined,
            },
        ],
    },
    // article 3
    {
        id: 3,
        title: '一觉醒来，满树的柑橘爬上了我的窗',
        desc: '做了一个关于加州的梦，我梦到我从梦中醒来，满树的柑橘爬上了我的窗。',
        tag: ['审美积累', '365天摄影计划', '洛杉矶', '滤镜调色', '治愈系风景', '手机壁纸'],
        dateTime: '2023-02-28 16:00',
        location: '美国',
        userId: 3,
        userName: '小小风筝',
        isFollow: false,
        avatarUrl: '/avatar/avatar_03.png',
        images: [
            '/article/article03/img_01.jpg',
            '/article/article03/img_02.jpg',
            '/article/article03/img_03.jpg',
            '/article/article03/img_04.jpg',
        ],
        favoriteCount: 18700,
        collectionCount: 2088,
        isFavorite: false,
        isCollection: false,
        comments: [
            {
                userName: 'ABC',
                avatarUrl: '/avatar/avatar_35.png',
                message: '忽然想起欧珑的那支香水，柑橘味的加州盛夏',
                dateTime: '2023-02-28 07:23',
                location: '成都',
                favoriteCount: 45,
                isFavorite: false,
                children: [
                    {
                        userName: '小小风筝',
                        avatarUrl: '/avatar/avatar_03.png',
                        message: '我还真的有这个',
                        dateTime: '2023-02-28 13:23',
                        location: '美国',
                        favoriteCount: 1,
                        isFavorite: false,
                    },
                ],
            },
            {
                userName: '仙女',
                avatarUrl: '/avatar/avatar_34.png',
                message: '这也太call me by your name了吧',
                dateTime: '2023-02-28 09:09',
                location: '福建',
                favoriteCount: 2,
                isFavorite: false,
                children: undefined,
            },
            {
                userName: 'Chery',
                avatarUrl: '/avatar/avatar_33.png',
                message: '微博也关注你了，没想到在小红书也看到你了',
                dateTime: '2023-02-28 11:11',
                location: '河南',
                favoriteCount: 3,
                isFavorite: false,
                children: undefined,
            },
            {
                userName: '时雨',
                avatarUrl: '/avatar/avatar_32.png',
                message: '本来有糟糕的情绪，看到这个风景一下子舒服了很多',
                dateTime: '2023-02-28 11:34',
                location: '山东',
                favoriteCount: 1,
                isFavorite: false,
                children: undefined,
            },
            {
                userName: '菠萝',
                avatarUrl: '/avatar/avatar_31.png',
                message: '啊啊啊啊啊啊好美，我宣布它将成为我下个阶段的手机壁纸',
                dateTime: '2023-02-28 11:35',
                location: '上海',
                favoriteCount: 0,
                isFavorite: false,
                children: undefined,
            },
            {
                userName: '圈圈',
                avatarUrl: '/avatar/avatar_30.png',
                message: '我已经闻到了清新的橘子的气息',
                dateTime: '2023-02-28 11:35',
                location: '河南',
                favoriteCount: 1,
                isFavorite: false,
                children: undefined,
            },
            {
                userName: 'Biss',
                avatarUrl: '/avatar/avatar_29.png',
                message: '好好看，求原图',
                dateTime: '2023-02-28 11:35',
                location: '北京',
                favoriteCount: 1,
                isFavorite: false,
                children: undefined,
            },
        ],
    },
    // article 4
    {
        id: 4,
        title: '满床清梦压星河',
        desc: '远处的小船越来越近\n船桨拨动着湖面激起涟漪\n在阳光下波光粼粼\n绘成了我心中的春日画',
        tag: ['治愈画面', '治愈风景', '笔记灵感', '摄影', '春天'],
        dateTime: '2023-03-03 11:00',
        location: '浙江',
        userId: 4,
        userName: '失忆',
        isFollow: false,
        avatarUrl: '/avatar/avatar_04.png',
        images: [
            '/article/article04/img_01.jpg',
            '/article/article04/img_02.jpg',
            '/article/article04/img_03.jpg',
            '/article/article04/img_04.jpg',
        ],
        favoriteCount: 8700,
        collectionCount: 288,
        isFavorite: true,
        isCollection: false,
        comments: [
            {
                userName: '纠结',
                avatarUrl: '/avatar/avatar_28.png',
                message: '我保存了图片，我要做手机壁纸',
                dateTime: '2023-02-28 07:23',
                location: '浙江',
                favoriteCount: 45,
                isFavorite: false,
                children: [
                    {
                        userName: '失忆',
                        avatarUrl: '/avatar/avatar_04.png',
                        message: '好的呦',
                        dateTime: '2023-02-28 13:23',
                        location: '浙江',
                        favoriteCount: 1,
                        isFavorite: false,
                    },
                ],
            },
            {
                userName: '貂貂',
                avatarUrl: '/avatar/avatar_27.png',
                message: '这是什么相机拍的，太好看了吧',
                dateTime: '2023-02-28 09:09',
                location: '福建',
                favoriteCount: 2,
                isFavorite: false,
                children: undefined,
            },
            {
                userName: '风风',
                avatarUrl: '/avatar/avatar_26.png',
                message: '这是西湖吗',
                dateTime: '2023-02-28 11:11',
                location: '河南',
                favoriteCount: 3,
                isFavorite: false,
                children: undefined,
            },
            {
                userName: '于桑',
                avatarUrl: '/avatar/avatar_25.png',
                message: '哇，这个图我刷到好几次了，是原作吗',
                dateTime: '2023-03-04 11:34',
                location: '山东',
                favoriteCount: 1,
                isFavorite: false,
                children: undefined,
            },
            {
                userName: '蘑菇',
                avatarUrl: '/avatar/avatar_24.png',
                message: '好漂亮',
                dateTime: '2023-02-28 11:35',
                location: '上海',
                favoriteCount: 0,
                isFavorite: false,
                children: undefined,
            },
            {
                userName: '煤球',
                avatarUrl: '/avatar/avatar_23.png',
                message: '太好看了吧',
                dateTime: '2023-02-28 11:35',
                location: '河南',
                favoriteCount: 1,
                isFavorite: false,
                children: undefined,
            },
            {
                userName: '尘埃',
                avatarUrl: '/avatar/avatar_22.png',
                message: '哇，你摄影技术好好啊',
                dateTime: '2023-02-28 11:35',
                location: '北京',
                favoriteCount: 1,
                isFavorite: false,
                children: undefined,
            },
        ],
    },
    // article 5
    {
        id: 5,
        title: '手机拍出来的星星，没想到那么多人喜欢',
        desc: '三月\n百花开\n红叶李打了头仗\n夜晚的它更晶莹剔透了\n散在空中\n像极了星星\n站在一片花朵的穹庐下',
        tag: ['拍照', '成都', '苹果手机', '春天', '三月'],
        dateTime: '2023-03-03 11:00',
        location: '成都',
        userId: 5,
        userName: '慢慢',
        isFollow: false,
        avatarUrl: '/avatar/avatar_05.png',
        images: [
            '/article/article05/img_01.jpg',
            '/article/article05/img_02.jpg',
            '/article/article05/img_03.jpg',
            '/article/article05/img_04.jpg',
            '/article/article05/img_05.jpg',
            '/article/article05/img_06.jpg',
            '/article/article05/img_07.jpg',
        ],
        favoriteCount: 2655,
        collectionCount: 288,
        isFavorite: false,
        isCollection: false,
        comments: [
            {
                userName: '心事',
                avatarUrl: '/avatar/avatar_22.png',
                message: '我姐姐朋友圈发了相同的图，真的好漂亮，今天又是想家的一天。',
                dateTime: '2023-02-28 07:23',
                location: '江西',
                favoriteCount: 12,
                isFavorite: false,
                children: [
                    {
                        userName: '慢慢',
                        avatarUrl: '/avatar/avatar_05.png',
                        message: '抱抱你',
                        dateTime: '2023-02-28 13:23',
                        location: '成都',
                        favoriteCount: 1,
                        isFavorite: false,
                    },
                ],
            },
            {
                userName: '木木',
                avatarUrl: '/avatar/avatar_21.png',
                message: '这哪里是星星啊，分明是我的梦',
                dateTime: '2023-02-28 09:09',
                location: '福建',
                favoriteCount: 2,
                isFavorite: false,
                children: undefined,
            },
            {
                userName: '你回来啦',
                avatarUrl: '/avatar/avatar_20.png',
                message: '可不可以出一下教程啊',
                dateTime: '2023-02-28 11:11',
                location: '河南',
                favoriteCount: 3,
                isFavorite: false,
                children: undefined,
            },
            {
                userName: '起风了',
                avatarUrl: '/avatar/avatar_19.png',
                message: '她的首页还有很多图',
                dateTime: '2023-03-04 11:34',
                location: '山东',
                favoriteCount: 1,
                isFavorite: false,
                children: undefined,
            },
            {
                userName: '山雾',
                avatarUrl: '/avatar/avatar_18.png',
                message: '这是什么花啊',
                dateTime: '2023-02-28 11:35',
                location: '上海',
                favoriteCount: 0,
                isFavorite: false,
                children: undefined,
            },
            {
                userName: '馨馨',
                avatarUrl: '/avatar/avatar_17.png',
                message: '怎么想到了水云天',
                dateTime: '2023-02-28 11:35',
                location: '河南',
                favoriteCount: 1,
                isFavorite: false,
                children: undefined,
            },
            {
                userName: '欢欢',
                avatarUrl: '/avatar/avatar_16.png',
                message: '等梨花开了就去拍照',
                dateTime: '2023-02-28 11:35',
                location: '北京',
                favoriteCount: 1,
                isFavorite: false,
                children: undefined,
            },
        ],
    },
    // article 6
    {
        id: 6,
        title: '告白如同田野间的风在青春里轰然',
        desc: '这次不上树改下田了\n果然还是喜欢短头发的自己\n大理春天啦\n有大片的油菜花和菜田\n亲眼看见风吹麦浪时，感觉自己好自由\n云也好美',
        tag: ['写真', '少女写真', '拍照姿势不重样', '短发', '青春'],
        dateTime: '2023-03-03 11:00',
        location: '云南',
        userId: 6,
        userName: '潇潇',
        isFollow: false,
        avatarUrl: '/avatar/avatar_06.png',
        images: [
            '/article/article06/img_01.jpg',
            '/article/article06/img_02.jpg',
            '/article/article06/img_03.jpg',
            '/article/article06/img_04.jpg',
            '/article/article06/img_05.jpg',
        ],
        favoriteCount: 2655,
        collectionCount: 288,
        isFavorite: false,
        isCollection: false,
        comments: [
            {
                userName: '小猫佳佳',
                avatarUrl: '/avatar/avatar_15.png',
                message: '第一张真的好看啊',
                dateTime: '2023-02-28 07:23',
                location: '江西',
                favoriteCount: 112,
                isFavorite: false,
                children: undefined,
            },
            {
                userName: '松鹤小登堡',
                avatarUrl: '/avatar/avatar_14.png',
                message: '首图真的太美了，扑面而来的自由气息和青春洋溢',
                dateTime: '2023-02-28 09:09',
                location: '云南',
                favoriteCount: 23,
                isFavorite: false,
                children: undefined,
            },
            {
                userName: '走走123',
                avatarUrl: '/avatar/avatar_13.png',
                message: '你好，我可以拿这个图片做头像吗？',
                dateTime: '2023-02-28 11:11',
                location: '河南',
                favoriteCount: 3,
                isFavorite: false,
                children: undefined,
            },
            {
                userName: '想看你a',
                avatarUrl: '/avatar/avatar_12.png',
                message: '万物自由生长，青春在旷野里窸窣作响。',
                dateTime: '2023-03-04 11:34',
                location: '云南',
                favoriteCount: 5,
                isFavorite: false,
                children: undefined,
            },
            {
                userName: '田字格',
                avatarUrl: '/avatar/avatar_11.png',
                message: '特别喜欢看宫崎骏的动画，喜欢里面的女孩子，身材比例和你一样，一度以为这只是动画人物，看到首图终于明白艺术源于生活。',
                dateTime: '2023-02-28 11:35',
                location: '山东',
                favoriteCount: 1112,
                isFavorite: false,
                children: undefined,
            },
            {
                userName: 'wasdbbb',
                avatarUrl: '/avatar/avatar_10.png',
                message: '第一眼还以为是宫崎骏的动画呢',
                dateTime: '2023-02-28 11:35',
                location: '河南',
                favoriteCount: 1,
                isFavorite: false,
                children: undefined,
            },
            {
                userName: '将秋叶',
                avatarUrl: '/avatar/avatar_09.png',
                message: '首图太美了吧，我要拿来当头像',
                dateTime: '2023-02-28 11:35',
                location: '北京',
                favoriteCount: 1,
                isFavorite: false,
                children: undefined,
            },
        ],
    },
    // article 7
    {
        id: 7,
        title: '那些很治愈人心的神仙句子',
        desc: '小舟从此逝，江海寄余生。\n幸得识君桃花面，从此阡陌多暖春。\n行到水穷处，坐看云起时。\n花开花落终有时，相逢相聚本无意。\n静待一树花开，盼你叶落归来。',
        tag: ['古诗词', '惊艳', '笔记', '灵感'],
        dateTime: '2023-03-04 12:00',
        location: '山东',
        userId: 7,
        userName: '青鸳',
        isFollow: false,
        avatarUrl: '/avatar/avatar_07.png',
        images: [
            '/article/article07/img_01.jpg',
            '/article/article07/img_02.jpg',
            '/article/article07/img_03.jpg',
            '/article/article07/img_04.jpg',
            '/article/article07/img_05.jpg',
        ],
        favoriteCount: 1998,
        collectionCount: 233,
        isFavorite: false,
        isCollection: false,
        comments: [],
    },
    // article 8
    {
        id: 8,
        title: '私藏影单，适合一个人看的32部文艺影片',
        desc: '我是钱多多，这里是钱多多的干货铺\n专注分享各领域的干货\n人海茫茫，有缘遇到，那就点赞关注收藏吧\n我们一起加油变得更加优秀',
        tag: ['笔记灵感', '解压技巧', '高分电影', '电影推荐', '女性成长'],
        dateTime: '2023-03-04 15:00',
        location: '云南',
        userId: 8,
        userName: '潇潇',
        isFollow: true,
        avatarUrl: '/avatar/avatar_08.png',
        images: [
            '/article/article08/img_01.jpg',
            '/article/article08/img_02.jpg',
            '/article/article08/img_03.jpg',
            '/article/article08/img_04.jpg',
            '/article/article08/img_05.jpg',
        ],
        favoriteCount: 2655,
        collectionCount: 288,
        isFavorite: false,
        isCollection: false,
        comments: [
            {
                userName: '江敏',
                avatarUrl: '/avatar/avatar_06.png',
                message: '蓝白红三部曲应该出现在你的片单里',
                dateTime: '2023-02-28 07:23',
                location: '上海',
                favoriteCount: 8,
                isFavorite: false,
                children: undefined,
            },
            {
                userName: 'Klok',
                avatarUrl: '/avatar/avatar_05.png',
                message: '王家卫、侯孝贤、李安也不错哦',
                dateTime: '2023-02-28 09:09',
                location: '云南',
                favoriteCount: 23,
                isFavorite: false,
                children: undefined,
            },
            {
                userName: '欢欢',
                avatarUrl: '/avatar/avatar_04.png',
                message: '春夏秋冬又一集',
                dateTime: '2023-02-28 11:11',
                location: '河南',
                favoriteCount: 3,
                isFavorite: false,
                children: undefined,
            },
            {
                userName: 'wild',
                avatarUrl: '/avatar/avatar_03.png',
                message: '最香民谣真的好好看啊！',
                dateTime: '2023-03-04 11:34',
                location: '云南',
                favoriteCount: 5,
                isFavorite: false,
                children: undefined,
            },
            {
                userName: 'slide',
                avatarUrl: '/avatar/avatar_02.png',
                message: '你的片单真的好，都是好电影，每一个都值得反复看几遍，支持支持！',
                dateTime: '2023-02-28 11:35',
                location: '山东',
                favoriteCount: 1112,
                isFavorite: false,
                children: undefined,
            },
            {
                userName: '毛衣',
                avatarUrl: '/avatar/avatar_01.png',
                message: '曾经有一份真挚的爱摆在我面前，而我没有珍惜，等到失去后才后悔莫及。',
                dateTime: '2023-02-28 11:35',
                location: '河南',
                favoriteCount: 1,
                isFavorite: false,
                children: undefined,
            },
        ],
    },
    // article 9
    {
        id: 9,
        title: '英国萨福克郡童话般的春日',
        desc: '大片的草地\n复古的建筑\n优美的环境\n清新的空气',
        tag: ['浪漫生活', '笔记灵感', '生活美学', '乡村生活', '英国乡村', '田园风', '田园生活', '乡村小屋', '童话风'],
        dateTime: '2023-03-05 12:12',
        location: '英国',
        userId: 9,
        userName: 'StiffKit',
        isFollow: true,
        avatarUrl: '/avatar/avatar_09.png',
        images: [
            '/article/article09/img_01.jpg',
            '/article/article09/img_02.jpg',
            '/article/article09/img_03.jpg',
            '/article/article09/img_04.jpg',
            '/article/article09/img_05.jpg',
            '/article/article09/img_06.jpg',
            '/article/article09/img_07.jpg',
        ],
        favoriteCount: 1244,
        collectionCount: 260,
        isFavorite: false,
        isCollection: false,
        comments: [
            {
                userName: 'stack',
                avatarUrl: '/avatar/avatar_40.png',
                message: '梦幻之地',
                dateTime: '2023-02-28 07:23',
                location: '上海',
                favoriteCount: 8,
                isFavorite: false,
                children: undefined,
            },
            {
                userName: '小霜霜',
                avatarUrl: '/avatar/avatar_39.png',
                message: '人越少的地方，越像童话',
                dateTime: '2023-03-05 13:09',
                location: '云南',
                favoriteCount: 23,
                isFavorite: false,
                children: undefined,
            },
            {
                userName: '夏威夷的风',
                avatarUrl: '/avatar/avatar_38.png',
                message: '这是我向往的生活',
                dateTime: '2023-03-05 11:11',
                location: '河南',
                favoriteCount: 3,
                isFavorite: false,
                children: undefined,
            },
            {
                userName: '舒心',
                avatarUrl: '/avatar/avatar_37.png',
                message: '好棒啊',
                dateTime: '2023-03-04 11:34',
                location: '云南',
                favoriteCount: 5,
                isFavorite: false,
                children: undefined,
            },
            {
                userName: 'JoJo',
                avatarUrl: '/avatar/avatar_36.png',
                message: '太美了这色调！',
                dateTime: '2023-03-05 11:35',
                location: '山东',
                favoriteCount: 1112,
                isFavorite: false,
                children: undefined,
            },
            {
                userName: '书草',
                avatarUrl: '/avatar/avatar_35.png',
                message: '好喜欢这地方，我想住过去',
                dateTime: '2023-02-28 11:35',
                location: '河南',
                favoriteCount: 1,
                isFavorite: false,
                children: undefined,
            },
        ],
    },
    // article 10
    {
        id: 10,
        title: '阳光洒进屋内，愿你每天早上都被阳光唤醒',
        desc: '大卫·斯坦尔得说，如果你想过上充满正能量的人生，那就直接表达感谢，延长幸福感。人不是因为喜悦而感谢，而是因为感谢而喜悦。每一天醒来迎接初升的太阳，看太阳东升西落，感受不同季节的温度和气息，每一天都与众不同。\n在铺满阳光的房间内，看窗前花开花落，原卷云舒，焚一炷香，泡一壶茶，捧一本书，享受冬日暖阳下惬意的时光。',
        tag: ['浪漫生活', '笔记灵感', '插画分享', '励志正能', '英国乡村', '田园风', '田园生活', '乡村小屋', '童话风'],
        dateTime: '2023-03-05 12:12',
        location: '广东',
        userId: 10,
        userName: '潇潇陌陌',
        isFollow: true,
        avatarUrl: '/avatar/avatar_10.png',
        images: [
            '/article/article10/img_01.jpg',
            '/article/article10/img_02.jpg',
            '/article/article10/img_03.jpg',
            '/article/article10/img_04.jpg',
            '/article/article10/img_05.jpg',
            '/article/article10/img_06.jpg',
            '/article/article10/img_07.jpg',
        ],
        favoriteCount: 3044,
        collectionCount: 1200,
        isFavorite: false,
        isCollection: false,
        comments: [
            {
                userName: '尔尔',
                avatarUrl: '/avatar/avatar_34.png',
                message: '忍不住点赞啊，真的好看',
                dateTime: '2023-02-28 07:23',
                location: '上海',
                favoriteCount: 8,
                isFavorite: false,
                children: undefined,
            },
            {
                userName: 'yoyo',
                avatarUrl: '/avatar/avatar_33.png',
                message: '现在的插画师越来越牛了',
                dateTime: '2023-03-05 13:09',
                location: '云南',
                favoriteCount: 23,
                isFavorite: false,
                children: undefined,
            },
            {
                userName: 'super',
                avatarUrl: '/avatar/avatar_32.png',
                message: '烤箱里面放柴火是吧',
                dateTime: '2023-03-05 11:11',
                location: '河南',
                favoriteCount: 3,
                isFavorite: false,
                children: undefined,
            },
            {
                userName: '小枫',
                avatarUrl: '/avatar/avatar_31.png',
                message: '虽然AI插画很强，但是我还是喜欢人画的，有灵魂在里面',
                dateTime: '2023-03-04 11:34',
                location: '云南',
                favoriteCount: 5,
                isFavorite: false,
                children: undefined,
            },
            {
                userName: '小怪兽',
                avatarUrl: '/avatar/avatar_30.png',
                message: '哈哈好喜欢这个地方啊',
                dateTime: '2023-03-05 11:35',
                location: '山东',
                favoriteCount: 1112,
                isFavorite: false,
                children: undefined,
            },
            {
                userName: '蓝莓',
                avatarUrl: '/avatar/avatar_29.png',
                message: '这样的环境是给仙女制造的',
                dateTime: '2023-02-28 11:35',
                location: '河南',
                favoriteCount: 1,
                isFavorite: false,
                children: undefined,
            },
        ],
    },
    // article 11
    {
        id: 11,
        title: '零碎的岛屿也能找到海',
        desc: '',
        tag: [],
        dateTime: '2023-03-05 12:12',
        location: '云南',
        userId: 11,
        userName: '觉觉子',
        isFollow: true,
        avatarUrl: '/avatar/avatar_11.png',
        images: [
            '/article/article11/img_01.jpg',
            '/article/article11/img_02.jpg',
            '/article/article11/img_03.jpg',
        ],
        favoriteCount: 105,
        collectionCount: 28,
        isFavorite: true,
        isCollection: false,
        comments: [
            {
                userName: '倪妮',
                avatarUrl: '/avatar/avatar_28.png',
                message: '这个博主太可爱了吧，关注了',
                dateTime: '2023-02-28 07:23',
                location: '上海',
                favoriteCount: 8,
                isFavorite: false,
                children: undefined,
            },
            {
                userName: '夏天',
                avatarUrl: '/avatar/avatar_27.png',
                message: '可以做头像吗，心情好好',
                dateTime: '2023-03-05 13:09',
                location: '云南',
                favoriteCount: 23,
                isFavorite: false,
                children: undefined,
            },
            {
                userName: '叮当',
                avatarUrl: '/avatar/avatar_26.png',
                message: '哇哦，我以为是宫崎骏的动画片',
                dateTime: '2023-03-05 11:11',
                location: '河南',
                favoriteCount: 3,
                isFavorite: false,
                children: undefined,
            },
            {
                userName: '某某',
                avatarUrl: '/avatar/avatar_25.png',
                message: '喜欢',
                dateTime: '2023-03-04 11:34',
                location: '云南',
                favoriteCount: 5,
                isFavorite: false,
                children: undefined,
            },
            {
                userName: '美美',
                avatarUrl: '/avatar/avatar_24.png',
                message: 'ai画的吧，好美啊',
                dateTime: '2023-03-05 11:35',
                location: '山东',
                favoriteCount: 1112,
                isFavorite: false,
                children: undefined,
            },
        ],
    },
    // article 12
    {
        id: 12,
        title: '16岁女高中生的日常',
        desc: '随手拍，无滤镜',
        tag: ['女高中生', '高中生活', '可爱'],
        dateTime: '2023-03-05 12:12',
        location: '北京',
        userId: 12,
        userName: '秋秋',
        isFollow: true,
        avatarUrl: '/avatar/avatar_12.png',
        images: [
            '/article/article12/img_01.jpg',
            '/article/article12/img_02.jpg',
            '/article/article12/img_03.jpg',
            '/article/article12/img_04.jpg',
        ],
        favoriteCount: 2010,
        collectionCount: 198,
        isFavorite: true,
        isCollection: false,
        comments: [
            {
                userName: 'yox',
                avatarUrl: '/avatar/avatar_23.png',
                message: '你知道女高中生的诱惑有多大吗',
                dateTime: '2023-02-28 07:23',
                location: '上海',
                favoriteCount: 8,
                isFavorite: false,
                children: undefined,
            },
            {
                userName: '上善若水',
                avatarUrl: '/avatar/avatar_22.png',
                message: '妈呀，好好看',
                dateTime: '2023-03-05 13:09',
                location: '云南',
                favoriteCount: 23,
                isFavorite: false,
                children: undefined,
            },
            {
                userName: 'Kuli',
                avatarUrl: '/avatar/avatar_21.png',
                message: '小姐姐好好看啊',
                dateTime: '2023-03-05 11:11',
                location: '河南',
                favoriteCount: 3,
                isFavorite: false,
                children: undefined,
            },
            {
                userName: '水波1kk',
                avatarUrl: '/avatar/avatar_20.png',
                message: '同高中生路过',
                dateTime: '2023-03-04 11:34',
                location: '云南',
                favoriteCount: 5,
                isFavorite: false,
                children: undefined,
            },
            {
                userName: '小野',
                avatarUrl: '/avatar/avatar_19.png',
                message: '高一纯情小奶狗路过',
                dateTime: '2023-03-05 11:35',
                location: '山东',
                favoriteCount: 1112,
                isFavorite: false,
                children: undefined,
            },
            {
                userName: '红薯',
                avatarUrl: '/avatar/avatar_18.png',
                message: '求联系方式',
                dateTime: '2023-02-28 11:35',
                location: '河南',
                favoriteCount: 1,
                isFavorite: false,
                children: undefined,
            },
        ],
    },
    // article 13
    {
        id: 13,
        title: '插画分享，治愈系',
        desc: '画中每一束照进来的阳光都是治愈系的味道',
        tag: ['插画分享', '治愈系插画', '治愈系'],
        dateTime: '2023-03-05 12:12',
        location: '广东',
        userId: 13,
        userName: 'PPUit',
        isFollow: true,
        avatarUrl: '/avatar/avatar_13.png',
        images: [
            '/article/article13/img_01.jpg',
            '/article/article13/img_02.jpg',
            '/article/article13/img_03.jpg',
            '/article/article13/img_04.jpg',
            '/article/article13/img_05.jpg',
        ],
        favoriteCount: 2010,
        collectionCount: 198,
        isFavorite: true,
        isCollection: false,
        comments: [
            {
                userName: '尔尔',
                avatarUrl: '/avatar/avatar_34.png',
                message: '忍不住点赞啊，真的好看',
                dateTime: '2023-02-28 07:23',
                location: '上海',
                favoriteCount: 8,
                isFavorite: false,
                children: undefined,
            },
            {
                userName: 'yoyo',
                avatarUrl: '/avatar/avatar_33.png',
                message: '现在的插画师越来越牛了',
                dateTime: '2023-03-05 13:09',
                location: '云南',
                favoriteCount: 23,
                isFavorite: false,
                children: undefined,
            },
            {
                userName: 'super',
                avatarUrl: '/avatar/avatar_32.png',
                message: '烤箱里面放柴火是吧',
                dateTime: '2023-03-05 11:11',
                location: '河南',
                favoriteCount: 3,
                isFavorite: false,
                children: undefined,
            },
            {
                userName: '小枫',
                avatarUrl: '/avatar/avatar_31.png',
                message: '虽然AI插画很强，但是我还是喜欢人画的，有灵魂在里面',
                dateTime: '2023-03-04 11:34',
                location: '云南',
                favoriteCount: 5,
                isFavorite: false,
                children: undefined,
            },
            {
                userName: '小怪兽',
                avatarUrl: '/avatar/avatar_30.png',
                message: '哈哈好喜欢这个地方啊',
                dateTime: '2023-03-05 11:35',
                location: '山东',
                favoriteCount: 1112,
                isFavorite: false,
                children: undefined,
            },
            {
                userName: '蓝莓',
                avatarUrl: '/avatar/avatar_29.png',
                message: '这样的环境是给仙女制造的',
                dateTime: '2023-02-28 11:35',
                location: '河南',
                favoriteCount: 1,
                isFavorite: false,
                children: undefined,
            },
        ],
    },
    // article 14
    {
        id: 14,
        title: '只有下班时间才能决定你的人生高度',
        desc: '不愧是央视推荐，每一个都是经典',
        tag: ['创业思维', '努力成为更好的自己', '不懂就问系列', '商业思维', '自我提升'],
        dateTime: '2023-03-05 12:12',
        location: '广东',
        userId: 14,
        userName: '创业笔记',
        isFollow: true,
        avatarUrl: '/avatar/avatar_14.png',
        images: [
            '/article/article14/img_01.jpg',
            '/article/article14/img_02.jpg',
            '/article/article14/img_03.jpg',
            '/article/article14/img_04.jpg',
            '/article/article14/img_05.jpg',
        ],
        favoriteCount: 2010,
        collectionCount: 198,
        isFavorite: false,
        isCollection: false,
        comments: [
            {
                userName: '华哥',
                avatarUrl: '/avatar/avatar_17.png',
                message: '毒鸡汤，下班了还不让人休息娱乐一下',
                dateTime: '2023-02-28 07:23',
                location: '上海',
                favoriteCount: 8,
                isFavorite: false,
                children: [
                    {
                        userName: '逆风',
                        avatarUrl: '/avatar/avatar_16.png',
                        message: '就是就是',
                        dateTime: '2023-02-28 08:23',
                        location: '上海',
                        favoriteCount: 1,
                        isFavorite: false,
                        children: undefined,
                    }
                ],
            },
            {
                userName: 'Xing',
                avatarUrl: '/avatar/avatar_15.png',
                message: '上班就已经够卷了，下班还要卷。',
                dateTime: '2023-02-28 07:23',
                location: '河南',
                favoriteCount: 8,
                isFavorite: false,
                children: undefined,
            },
        ],
    },
    // article 15
    {
        id: 15,
        title: '飞行小柯基来喽',
        desc: '萌宠小柯基，起飞上天喽～',
        tag: ['狗狗', '我家宠物', '可爱壁纸'],
        dateTime: '2023-03-05 12:12',
        location: '内蒙古',
        userId: 15,
        userName: '小小画童',
        isFollow: true,
        avatarUrl: '/avatar/avatar_15.png',
        images: [
            '/article/article15/img_01.jpg',
            '/article/article15/img_02.jpg',
            '/article/article15/img_03.jpg',
            '/article/article15/img_04.jpg',
        ],
        favoriteCount: 340,
        collectionCount: 66,
        isFavorite: false,
        isCollection: false,
        comments: [
            {
                userName: 'CCHHOO',
                avatarUrl: '/avatar/avatar_14.png',
                message: '我可以拿来当头像吗',
                dateTime: '2023-02-28 07:23',
                location: '广东',
                favoriteCount: 8,
                isFavorite: false,
                children: [
                    {
                        userName: '小小画童',
                        avatarUrl: '/avatar/avatar_15.png',
                        message: '当然可以啊',
                        dateTime: '2023-02-28 07:23',
                        location: '内蒙古',
                        favoriteCount: 1,
                        isFavorite: false,
                        children: undefined,
                    }
                ],
            },
            {
                userName: '火锅',
                avatarUrl: '/avatar/avatar_13.png',
                message: '王牌飞行员申请出战',
                dateTime: '2023-03-05 13:09',
                location: '云南',
                favoriteCount: 23,
                isFavorite: false,
                children: undefined,
            },
            {
                userName: '柴瘥',
                avatarUrl: '/avatar/avatar_12.png',
                message: '太可爱了吧',
                dateTime: '2023-03-05 11:11',
                location: '河南',
                favoriteCount: 3,
                isFavorite: false,
                children: undefined,
            },
            {
                userName: '甜甜',
                avatarUrl: '/avatar/avatar_13.png',
                message: '可爱，想要看雪纳瑞飞行员',
                dateTime: '2023-03-04 11:34',
                location: '云南',
                favoriteCount: 5,
                isFavorite: false,
                children: undefined,
            },
            {
                userName: 'CoCo',
                avatarUrl: '/avatar/avatar_12.png',
                message: '喜欢，点赞点赞',
                dateTime: '2023-03-05 11:35',
                location: '山东',
                favoriteCount: 1112,
                isFavorite: false,
                children: undefined,
            },
        ],
    },
];

export default articles;