const goods: GoodsSimple[] = [
    {
        id: 1,
        title: '纯小麦粉面粉无小麦麸质低脂杂粮糖友敏宝牛油果果桥本·700g*3袋装',
        image: '/goods/goods01/img_01.jpg',
        price: 51,
        originPrice: undefined,
        promotion: undefined,
    },
    {
        id: 2,
        title: '糙米米粉江西米线南仓拌粉螺狮粉800g粗粮无小麦麸',
        image: '/goods/goods02/img_01.jpg',
        price: 84,
        originPrice: undefined,
        promotion: undefined,
    },
    {
        id: 3,
        title: '手作一鸣禅意大合集9.9r全新款绕指柔串12mm圆珠抹茶芝士大合集',
        image: '/goods/goods03/img_01.jpg',
        price: 9.9,
        originPrice: 12.8,
        promotion: undefined,
    },
    {
        id: 4,
        title: '山核桃手串文玩核桃手串手持珠串小核桃串手挂可爆浆深山采核桃',
        image: '/goods/goods04/img_01.jpg',
        price: 9.9,
        originPrice: undefined,
        promotion: undefined,
    },
    {
        id: 5,
        title: '纯色素珠5.6R拼手速·纯绿11*12mm',
        image: '/goods/goods05/img_01.jpg',
        price: 5.8,
        originPrice: undefined,
        promotion: undefined,
    },
    {
        id: 6,
        title: '天然绿檀木佛珠手串老料和田玉檀香木链男女民族饰品手串',
        image: '/goods/goods06/img_01.jpg',
        price: 12,
        originPrice: undefined,
        promotion: undefined,
    },
    {
        id: 7,
        title: '黄油椰子素酥咸蛋黄酥脆饼干椰蓉酥糕点零食酥到没朋友咖啡椰子酥',
        image: '/goods/goods07/img_01.jpg',
        price: 15.8,
        originPrice: undefined,
        promotion: '满100减18',
    },
    {
        id: 8,
        title: '厚切吐司面包奶香味提拉米苏味手撕面包14袋整箱装混合口味',
        image: '/goods/goods08/img_01.jpg',
        price: 19.9,
        originPrice: 25.98,
        promotion: undefined,
    },
    {
        id: 9,
        title: '圆包洋车前子壳粉膳食纤维烘焙生酮无小麦麸质0脂250g*2袋装',
        image: '/goods/goods09/img_01.jpg',
        price: 76,
        originPrice: undefined,
        promotion: '满240减50',
    },
    {
        id: 10,
        title: '广西荔浦水果马蹄荸荠当季零食蔬菜保证新鲜批发价包邮5近王中王',
        image: '/goods/goods10/img_01.jpg',
        price: 75,
        originPrice: undefined,
        promotion: undefined,
    },
    {
        id: 11,
        title: '夏天水洗全棉纯色日系棒球帽男女黑色韩版软定鸭舌帽军绿色可调节',
        image: '/goods/goods11/img_01.jpg',
        price: 14,
        originPrice: 18.8,
        promotion: undefined,
    },
    {
        id: 12,
        title: '纯肉桂粉65g桂皮天然调料冲饮烘焙健身拿铁黄金奶茶桥本65g*2瓶',
        image: '/goods/goods12/img_01.jpg',
        price: 29,
        originPrice: undefined,
        promotion: undefined,
    },
    {
        id: 13,
        title: '樱花虾米饼非油炸谷物米饼脆香辣味',
        image: '/goods/goods13/img_01.jpg',
        price: 11.8,
        originPrice: undefined,
        promotion: undefined,
    },
    {
        id: 14,
        title: '芒果奶糕草莓干之恋牛扎奶芙芒果干芒果控推荐',
        image: '/goods/goods14/img_01.jpg',
        price: 38.6,
        originPrice: undefined,
        promotion: undefined,
    },
    {
        id: 15,
        title: '精品葫芦·直播间选购',
        image: '/goods/goods15/img_01.jpg',
        price: 9.9,
        originPrice: undefined,
        promotion: undefined,
    },
    {
        id: 16,
        title: '天然菩提手串三顶菩提根文玩女佛珠手串奶芒12*11mm',
        image: '/goods/goods16/img_01.jpg',
        price: 19.9,
        originPrice: undefined,
        promotion: undefined,
    },
    {
        id: 17,
        title: '老北京驴打滚糯米糍粑打年糕东北特产豆面卷休闲小吃即食零食450g',
        image: '/goods/goods17/img_01.jpg',
        price: 14.9,
        originPrice: 19.9,
        promotion: undefined,
    },
    {
        id: 18,
        title: '奥德斯可可脂原味黑巧克力杏仁夹心巧克力纯手工烘焙网红休闲零食原味方形',
        image: '/goods/goods18/img_01.jpg',
        price: 10.8,
        originPrice: 12.98,
        promotion: undefined,
    },
    {
        id: 19,
        title: '轻盈一夏慢碳水套餐全麦荞麦面鸡胸肉丸全麦面包黑咖啡肉肠',
        image: '/goods/goods19/img_01.jpg',
        price: 39.9,
        originPrice: undefined,
        promotion: undefined,
    },
    {
        id: 20,
        title: '【2个装】现代简约浮雕纹玻璃花瓶透明鲜花插花瓶冰川纹',
        image: '/goods/goods20/img_01.jpg',
        price: 9.9,
        originPrice: undefined,
        promotion: undefined,
    },
];

export const top10Category = [
    {id: 1, name: '潮流买手店', image: '/goods/top10/top1.jpg'},
    {id: 2, name: '新趋势', image: '/goods/top10/top2.jpg'},
    {id: 3, name: '福利社', image: '/goods/top10/top3.jpg'},
    {id: 4, name: '小绿洲', image: '/goods/top10/top4.jpg'},
    {id: 5, name: '宝藏好店', image: '/goods/top10/top5.jpg'},
    {id: 6, name: '独特设计', image: '/goods/top10/top6.jpg'},
    {id: 7, name: '芭蕾风女孩', image: '/goods/top10/top7.jpg'},
    {id: 8, name: '清幽茶木香', image: '/goods/top10/top8.jpg'},
    {id: 9, name: '踏青必备', image: '/goods/top10/top9.jpg'},
    {id: 10, name: '青春出行', image: '/goods/top10/to10.jpg'},
];

export default goods;